/// <reference lib="deno.ns" />

const outputFile = new URL("../src/lib/index.ts", import.meta.url);
const componentsDir = new URL("../src/lib/components/", import.meta.url);
const iconsDir = new URL("../src/lib/components/icons/", import.meta.url);

const exportsFor = async (
    directory: URL,
    importPath: string,
): Promise<string[]> => {
    const exports: string[] = [];

    for await (const entry of Deno.readDir(directory)) {
        if (!entry.isFile || !entry.name.endsWith(".svelte")) {
            continue;
        }

        const name = entry.name.replace(/\.svelte$/, "");

        exports.push(
            `export { default as ${name} } from "${importPath}/${entry.name}";`,
        );
    }

    return exports.sort();
};

const index = [
    "// This file is automatically generated. Do not edit it manually.",
    "// Run `pnpm run generate:index` to regenerate this file.",
    "",
    ...await exportsFor(componentsDir, "./components"),
    "",
    ...await exportsFor(iconsDir, "./components/icons"),
    "",
].join("\n");

await Deno.writeTextFile(outputFile, index);
